<a href="https://colab.research.google.com/github/vahid-saffarian/mlsandbox/blob/master/ML_Recipe_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
iris_idx = [0, 50, 100]

#train set
train_target = np.delete(iris.target, iris_idx)
train_data = np.delete(iris.data, iris_idx, axis = 0)

#test set
test_target = iris.target[iris_idx]
test_data = iris.data[iris_idx]

#traing the model
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

#testing
prediction = clf.predict(test_data)
print(test_target)
print(prediction)

print(test_data[1], test_target[1])

print(iris.feature_names, iris.target_names)



[0 1 2]
[0 1 2]
[7.  3.2 4.7 1.4] 1
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
